// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5AJ9jd5iEESXfRe5ufKRDtTBn9B1p9E',
    appId: '1:865596431408:web:f4dcd0b07ee70b7cdb61f5',
    messagingSenderId: '865596431408',
    projectId: 'demoproject-b0b4a',
    authDomain: 'demoproject-b0b4a.firebaseapp.com',
    storageBucket: 'demoproject-b0b4a.appspot.com',
    measurementId: 'G-HP330JGG65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpdOz3d3OChUHFLxpQLtmjAnGBraDrwDM',
    appId: '1:865596431408:android:c76ca75d0ff4d4b2db61f5',
    messagingSenderId: '865596431408',
    projectId: 'demoproject-b0b4a',
    storageBucket: 'demoproject-b0b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQS4gmBcV2KJIPS-uFhDcoGmgaLgX-rZw',
    appId: '1:865596431408:ios:72f8ef92f4712f7adb61f5',
    messagingSenderId: '865596431408',
    projectId: 'demoproject-b0b4a',
    storageBucket: 'demoproject-b0b4a.appspot.com',
    iosClientId: '865596431408-trv4p1nbn43ogl033mko3ta8dofhatr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQS4gmBcV2KJIPS-uFhDcoGmgaLgX-rZw',
    appId: '1:865596431408:ios:72f8ef92f4712f7adb61f5',
    messagingSenderId: '865596431408',
    projectId: 'demoproject-b0b4a',
    storageBucket: 'demoproject-b0b4a.appspot.com',
    iosClientId: '865596431408-trv4p1nbn43ogl033mko3ta8dofhatr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoproject',
  );
}
